# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # ...
    admin.book:
        class: AppBundle\Admin\BookAdmin
        arguments: [~, AppBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Book }
    
    admin.book_type:
        class: AppBundle\Admin\BookTypeAdmin
        arguments: [~, AppBundle\Entity\BookType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: BookType } 
    
    admin.brova:
        class: AppBundle\Admin\BrovaAdmin
        arguments: [~, AppBundle\Entity\Brova, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Brova } 
    
    admin.category:
        class: AppBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Category} 
            
    admin.cover:
        class: AppBundle\Admin\CoverAdmin
        arguments: [~, AppBundle\Entity\Cover, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cover } 