# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    # ...
    admin.book:
        class: AppBundle\Admin\BookAdmin
        arguments: [~, AppBundle\Entity\Book, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Book }
    
    admin.book_type:
        class: AppBundle\Admin\BookTypeAdmin
        arguments: [~, AppBundle\Entity\BookType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: BookType }        